export const GET_USER_LIST_SUCCESS = 'GET_USER_LIST_SUCCESS';
export const GET_USER_LIST_FAILURE = 'GET_USER_LIST_FAILURE';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';

export const GET_AUTH_FAILURE = 'GET_AUTH_FAILURE';
export const GET_AUTH_SUCCESS = 'GET_AUTH_SUCCESS'; 

export const GET_PRODUCT_LIST_SUCCESS = 'GET_PRODUCT_LIST_SUCCESS'
export const GET_PRODUCT_LIST_FAILURE = 'GET_PRODUCT_LIST_FAILURE'
export const GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE'
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS'

export const GET_CATEGORY_LIST_SUCCESS = 'GET_CATEGORY_LIST_SUCCESS'
export const GET_CATEGORY_LIST_FAILURE = 'GET_CATEGORY_LIST_FAILURE'
export const GET_CATEGORY_FAILURE = 'GET_CATEGORY_FAILURE'
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS'

export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';

export const GET_DASHBOARD_LIST_SUCCESS = 'GET_DASHBOARD_LIST_SUCCESS'
export const GET_DASHBOARD_LIST_FAILURE = 'GET_DASHBOARD_LIST_FAILURE'
export const GET_DASHBOARD_FAILURE = 'GET_DASHBOARD_FAILURE'
export const GET_DASHBOARD_SUCCESS = 'GET_DASHBOARD_SUCCESS'

export const GET_SUPPORT_LIST_SUCCESS = 'GET_SUPPORT_LIST_SUCCESS'
export const GET_SUPPORT_LIST_FAILURE = 'GET_SUPPORT_LIST_FAILURE'
export const GET_SUPPORT_FAILURE = 'GET_SUPPORT_FAILURE'
export const GET_SUPPORT_SUCCESS = 'GET_SUPPORT_SUCCESS'

export const GET_NOTIFICATION_LIST_SUCCESS = 'GET_NOTIFICATION_LIST_SUCCESS'
export const GET_NOTIFICATION_LIST_FAILURE = 'GET_NOTIFICATION_LIST_FAILURE'
export const GET_NOTIFICATION_FAILURE = 'GET_NOTIFICATION_FAILURE'
export const GET_NOTIFICATION_SUCCESS = 'GET_NOTIFICATION_SUCCESS'
export const UPDATE_NOTIFICATION_SUCCESS = 'UPDATE_NOTIFICATION_SUCCESS'

export const GET_PAYMENT_LIST_SUCCESS = 'GET_PAYMENT_LIST_SUCCESS'
export const GET_PAYMENT_LIST_FAILURE = 'GET_PAYMENT_LIST_FAILURE'
export const GET_PAYMENT_FAILURE = 'GET_PAYMENT_FAILURE'
export const GET_PAYMENT_SUCCESS = 'GET_PAYMENT_SUCCESS'


export const GET_AREA_LIST_SUCCESS = 'GET_AREA_LIST_SUCCESS'
export const GET_AREA_LIST_FAILURE = 'GET_AREA_LIST_FAILURE'
export const GET_AREA_FAILURE = 'GET_AREA_FAILURE'
export const GET_AREA_SUCCESS = 'GET_AREA_SUCCESS'

export const GET_CIVILSTATE_LIST_SUCCESS = 'GET_CIVILSTATE_LIST_SUCCESS'
export const GET_CIVILSTATE_LIST_FAILURE = 'GET_CIVILSTATE_LIST_FAILURE'
export const GET_CIVILSTATE_FAILURE = 'GET_CIVILSTATE_FAILURE'
export const GET_CIVILSTATE_SUCCESS = 'GET_CIVILSTATE_SUCCESS'

export const GET_COMMONQUESTION_LIST_SUCCESS = 'GET_COMMONQUESTION_LIST_SUCCESS'
export const GET_COMMONQUESTION_LIST_FAILURE = 'GET_COMMONQUESTION_LIST_FAILURE'
export const GET_COMMONQUESTION_FAILURE = 'GET_COMMONQUESTION_FAILURE'
export const GET_COMMONQUESTION_SUCCESS = 'GET_COMMONQUESTION_SUCCESS'

export const GET_COMPLAINT_LIST_SUCCESS = 'GET_COMPLAINT_LIST_SUCCESS'
export const GET_COMPLAINT_LIST_FAILURE = 'GET_COMPLAINT_LIST_FAILURE'
export const GET_COMPLAINT_FAILURE = 'GET_COMPLAINT_FAILURE'
export const GET_COMPLAINT_SUCCESS = 'GET_COMPLAINT_SUCCESS'

export const GET_NATIONALITY_LIST_SUCCESS = 'GET_NATIONALITY_LIST_SUCCESS'
export const GET_NATIONALITY_LIST_FAILURE = 'GET_NATIONALITY_LIST_FAILURE'
export const GET_NATIONALITY_FAILURE = 'GET_NATIONALITY_FAILURE'
export const GET_NATIONALITY_SUCCESS = 'GET_NATIONALITY_SUCCESS'

export const GET_NEWS_LIST_SUCCESS = 'GET_NEWS_LIST_SUCCESS'
export const GET_NEWS_LIST_FAILURE = 'GET_NEWS_LIST_FAILURE'
export const GET_NEWS_FAILURE = 'GET_NEWS_FAILURE'
export const GET_NEWS_SUCCESS = 'GET_NEWS_SUCCESS'

export const GET_ORGAN_LIST_SUCCESS = 'GET_ORGAN_LIST_SUCCESS'
export const GET_ORGAN_LIST_FAILURE = 'GET_ORGAN_LIST_FAILURE'
export const GET_ORGAN_FAILURE = 'GET_ORGAN_FAILURE'
export const GET_ORGAN_SUCCESS = 'GET_ORGAN_SUCCESS'

export const GET_PROMOTION_LIST_SUCCESS = 'GET_PROMOTION_LIST_SUCCESS'
export const GET_PROMOTION_LIST_FAILURE = 'GET_PROMOTION_LIST_FAILURE'
export const GET_PROMOTION_FAILURE = 'GET_PROMOTION_FAILURE'
export const GET_PROMOTION_SUCCESS = 'GET_PROMOTION_SUCCESS'

export const GET_SCHEDULE_LIST_SUCCESS = 'GET_SCHEDULE_LIST_SUCCESS'
export const GET_SCHEDULE_LIST_FAILURE = 'GET_SCHEDULE_LIST_FAILURE'
export const GET_SCHEDULE_FAILURE = 'GET_SCHEDULE_FAILURE'
export const GET_SCHEDULE_SUCCESS = 'GET_SCHEDULE_SUCCESS'

export const GET_SEX_LIST_SUCCESS = 'GET_SEX_LIST_SUCCESS'
export const GET_SEX_LIST_FAILURE = 'GET_SEX_LIST_FAILURE'
export const GET_SEX_FAILURE = 'GET_SEX_FAILURE'
export const GET_SEX_SUCCESS = 'GET_SEX_SUCCESS'

export const GET_SUBJECT_LIST_SUCCESS = 'GET_SUBJECT_LIST_SUCCESS'
export const GET_SUBJECT_LIST_FAILURE = 'GET_SUBJECT_LIST_FAILURE'
export const GET_SUBJECT_FAILURE = 'GET_SUBJECT_FAILURE'
export const GET_SUBJECT_SUCCESS = 'GET_SUBJECT_SUCCESS'